SET SCHEMA FN45708;

CREATE TABLE EMPLOYEE LIKE DB2INST1.EMPLOYEE;
INSERT INTO EMPLOYEE SELECT * FROM DB2INST1.EMPLOYEE;
ALTER TABLE EMPLOYEE ADD PRIMARY KEY (EMPNO);

SELECT * FROM EMPLOYEE;

CREATE TRIGGER FN45708.EMPLOYEE_SALARY
    BEFORE INSERT ON FN45708.EMPLOYEE
    REFERENCING NEW AS N
    FOR EACH ROW
    WHEN (N.SALARY < 10000) SET N.SALARY = 30000;

SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE
VALUES(200000, ASSASS, DSA, K, DSA, NULL, NULL,NULL, NULL, NULL, NULL, 5000, NULL, NULL);